<?php

namespace Domain;

use Doctrine\ORM\EntityRepository;

/**
 * BillRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class BillRepository extends EntityRepository
{

}
