<html>

<head>

    <title>adShow</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css"
          integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
</head>

<body class="container-fluid text-monospace p-0 m-0" >

<div class="header fixed-top text-center pt-5 text-white">
    <p> Free tissue </p>
</div>

<img src="/test/header.jpg" class="img-fluid" alt="Responsive image" width="100%">

<section style="height: 50%;line-height: 50%;">

    <div class="text-center p-3"
         style="background: url('/test/imgbuild-200.png') no-repeat center;">
        <div class="pt-4 pb-4 pl-5 pr-4">
            <img src="https://mp.weixin.qq.com/cgi-bin/showqrcode?ticket=gQFL7zwAAAAAAAAAAS5odHRwOi8vd2VpeGluLnFxLmNvbS9xLzAyeFBiU2NmanJkRWsxMGtLeTFyY1QAAgQURRpbAwQA6QcA" alt="adCode" class="img-fluid" width="155px">
        </div>
    </div>
    <div class="text-center mt-2 p-3" style="color: #b5b1ff;background: url('/test/tipIcon.jpg') no-repeat center;">
        <p>回复<strong style="font-size: 2rem; ">888</strong>免费领纸</p>
    </div>

</section>

<footer class="footer fixed-bottom">
    <div class="text-center">
        <button type="button" class="btn btn-sm "
                style="border-color:#aeb8ff;background-color: #aeb8ff;border-radius: 20%;
		color: #eff7ff;box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2), 0 6px 20px 0 rgba(0,0,0,0.19); ">买一包</button>
    </div>
    <img src="/test/footer.jpg" class="img-fluid" alt="Responsive image" width="100%">
</footer>
</body>

</html>
