<html>

<head>

    <title>fail</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css"
          integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
</head>

<body class="container-fluid text-monospace p-0 m-0" >
<div class="header fixed-top text-center pt-5 text-white">
    <p> Free tissue </p>
</div>
<img src="/test/header.jpg" class="img-fluid" alt="Responsive image" width="100%">

<section  style="height: %;line-height: 50%;">

    <div class="mx-auto" >
        <img src="/test/failIcon.jpg" class="img-fluid" alt="Responsive image" width="100%">
    </div>

    <div class="text-center text-primary" >
        <h4>领取失败</h4>
        <p class="small">Receive success</p>
    </div>

</section>

<footer class="footer fixed-bottom">
    <div class="text-center">
        <p class="m-0 p-0 text-primary">客服: <a href="tel:18027133575" class="">18027133575</a></p>
        <span class="m-0 p-0 small text-muted" >Copyright< 2018纸色</span>
    </div>
    <img src="/test/footer.jpg" class="img-fluid" alt="Responsive image" width="100%">
</footer>
</body>

</html>