<html>

<head>

    <title>offline</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css"
          integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
</head>

<body class="container-fluid text-monospace p-0 m-0" >

<div class="header fixed-top text-center pt-5 text-white">
    <p> Free tissue </p>
</div>

<img src="/test/header.jpg" class="img-fluid" alt="Responsive image" width="100%">

<section  style="height: 50%;line-height: 50%; padding-top: 25%;">

    <div class="text-center text-primary" >
        <h4 >设备离线中</h4>
        <p class="small">The equipment is offline </p>
        <p class="small">Please try it against </p>
    </div>

</section>

<footer class="footer fixed-bottom">
    <div class="text-center">
        <p class="m-0 p-0 text-primary">客服: <a href="tel:18027133575" class="">18027133575</a></p>
        <span class="m-0 p-0 small text-muted" >Copyright< 2018纸色</span>
    </div>
    <img src="/test/footer.jpg" class="img-fluid" alt="Responsive image" width="100%">
</footer>
</body>

</html>